# Generated by Django 3.1.3 on 2020-11-06 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, null=True)),
                ('profile_pic', django_resized.forms.ResizedImageField(blank=True, crop=None, default='profile.png', force_format='JPEG', keep_meta=True, null=True, quality=75, size=[90, 90], upload_to='')),
                ('profession', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True, max_length=250)),
                ('country', models.CharField(blank=True, choices=[('INDIA', 'INDIA'), ('USA', 'USA'), ('NEW YORK', 'NEW YORK')], max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
